[package]
name = "concurrentgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guarded = { path = "../guarded" }
magnitude = "0.3.2"